export default new Map([
	['text', 'text/plain'],
	['html', 'text/html'],
	['css', 'text/css'],
	['csv', 'text/csv'],
	['js', 'text/javascript'],
	['gif', 'image/gif'],
	['jpeg', 'image/jpeg'],
	['png', 'image/png'],
	['svg', 'image/svg+xml'],
	['midi', 'audio/midi'],
	['mp3', 'audio/mpeg'],
	['oga', 'audio/ogg'],
	['mp4', 'video/mp4'],
	['mpeg', 'video/mpeg'],
	['ogv', 'video/ogg'],
	['zip', 'application/zip'],
	['pdf', 'application/pdf'],
	['epub', 'application/epub+zip'],
	['gz', 'application/gzip'],
	['bin', 'application/octet-stream'],
	['json', 'application/json'],
	['jsonld', 'application/ld+json'],
]);
